### ISSUE TITLE
Document how to set up the app

### ISSUE THREAD

**Issue by romac** [reminisceme/game-creator#1]
It would be awesome if you could document how to set up the app and its dependencies (if any) in the README (or some other doc in the repository).

**Comment by Aranir** [comment]
Added a first description.

Let me know if anything is unclear or needs further explanation.

**Comment by romac** [comment]
There's everything needed, thanks :)

Only issue now is that we don't have enough RAM on the droplet to launch sbt (same problem with `crawler`): 

```
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00000000b0000000, 357892096, 0) failed; error='Cannot allocate memory' (errno=12)
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (malloc) failed to allocate 357892096 bytes for committing reserved memory.
# An error report file with more information is saved as:
# /var/apps/game-creator/hs_err_pid8022.log
```

I'll try to `assemble` the JAR locally and only run it on the host but I'm not hopeful. I'll upgrade the droplet to 1GB RAM (let's hope it's gonna be enough for both `crawler` and `game-creator`).

**Comment by Aranir** [comment]
I used upstart on the server and created the corresponding services:

    sudo service game-creator start
    sudo service game-creator stop

This should limit the ram to 128, but we still ran into memory problems.

Maybe that helps

**Comment by romac** [comment]
Oh sweet!  

We should document that kind of thing somewhere in the wiki.

I’ll see how it goes, and will upgrade the droplet if necessary.  

--  
Romain Ruetschi

https://romac.me

**Comment by pirroh** [comment]
Reopening this, to make sure we don't forget about the upstart recipe!
@Aranir: can you document this step in the README, and include scripts (if any) directly in the repo? (maybe in a deploy/ directory)

**Comment by Rabyss** [comment]
A lot changed since this issue was last discussed, I will document the deployment process before the end of the week, feel free to ping me before if necessary.

**Comment by Rabyss** [comment]
I added a document to explain how to deploy the app on Amazon Elastic Beanstalk. To run a local version you can simply follow the install guide.
