### ISSUE TITLE
Logging bug in the stats generator

### ISSUE THREAD

**Issue by Rabyss** [reminisceme/game-creator#57]
Removing the line here:
https://github.com/reminisceme/game-creator/pull/55/files#diff-ec331805c011ac41b390f2d320730071L20

Seems to make the `log` reference `null` here:
https://github.com/reminisceme/game-creator/blob/master/src/main/scala/me/reminisce/stats/StatsGenerator.scala#L314

**Comment by Rabyss** [comment]
@vincenzobaz could you look into this?

**Comment by vincenzobaz** [comment]
Do you have a null pointer exception?
How can I reproduce the bug?

**Comment by Rabyss** [comment]
I get a null pointer exception (saying `log` is `null`).

You can see it by running `sbt it:test`
